# Lootable Corpses config

# Set in minutes how many minutes before corpses are removed
# Set to 0 to not remove corpses automatically
remove-corpse-after-minutes: 2

# Set in minutes how many minutes before corpses are removed after interaction
# Set to 0 to remove instantly after interaction
# Set to -1 to disable
remove-corpse-after-interaction-minutes: 0

# Disable looting corpses
disable-looting: false

# Instant respawn - cancel death screen
instant-respawn: true

# Kill players when leaving game
kill-on-leave: false

# Drop inventory when corpse despawns
# This will be disabled if you have remove-corpse-after-interaction-minutes set to 0
drop-inv-on-despawn: false

# Custom inventory title
inventory-title: "{player}'s inventory"

# Set whether the corpse is generated above the Void when a player dies in the Void
keep-corpses-above-the-void: true

# Set to true to spawn a corpse when a player leaves the game without killing the player
# Note: This will clear the player's inventory, it is up to them to retake their inventory from their corpse on rejoin
# Note: kill-on-leave must be false for this to be enabled
spawn-corpse-on-player-leave: false

# Blacklisted worlds - disable lootable corpses in certain worlds
blacklisted-worlds:
  - world_nether